---
- name: 환경파일 배포
  hosts: all
  gather_facts: no
  remote_user: devops
  become: false
  tasks:
  - name: 환경 파일 배포 $HOME/.bashrc
    template:
      src: templates/bashrc.j2
      dest: .bashrc

  - name: 디렉토리 복사
    copy:
      src: files/blesh
      dest: .local/share
