---
# (ㄱ) 패키지 설치
#   # yum install httpd
# (ㄴ) 서비스 설정
#   # cp files/index.html /var/www/html/index.html
# (ㄷ) 서비스 기동
#   # systemctl enable --now httpd
# (ㄹ) 방화벽 기동
# (?) SELinux

- name: Install and start Apache HTTPD
  hosts: webservers
  tasks:
  - name: httpd package is present
    yum:
      name:
        - httpd
        - mod_ssl
      state: latest

  - name:  correct index.html is present
    copy:
      src: files/index.html
      dest: /var/www/html/index.html

  - name: httpd is started
    service:
      name: httpd
      state: started
      enabled: true
      
  - name: Firewall configure
    firewalld:
      service: http
      permanent: yes
      immediate: yes
      state: enabled