---
- name: DB 패키지 삭제
  hosts: all
  gather_facts: no
  vars_files:
    - vars/db.yml
  tasks:
    - name: db 서비스 종료
      service:
        name: "{{ svc_db }}"
        state: stopped
        enabled: no
      ignore_errors: yes
    - name: DB 패키지 삭제
      yum:
        name: "{{ pkg_db }}"
        state: absent

    - name: /etc/my.cnf 파일 삭제
      file:
        path: "{{ conf_dest_file }}"
        state: absent
