---
# 평문 비밀번호를 암호화해서 생성
- name: 사용자 추가
  hosts: devservers
  remote_user: devops
  become: true
  vars_files:
    - vars/secret.yml
  tasks:
  - name: 다중 사용자 추가 및 암호 설정
    user:
      name: "{{  item.name }}"
      password: "{{ item.pw | password_hash('sha512') }}"
      # "{{ item.pw | 암호화 하기('암호화방식') }}"
    with_items:
    # loop와 같은 기능이지만 쪼개서 받을 수 있다...?
      - "{{ newusers }}"
